apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: products-ms
  name: products-ms
spec:
  ports:
  - name: "3001"
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: products-ms
  type: NodePort
status:
  loadBalancer: {}
